//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I95Dev.Connector.UI.Base.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I95Dev.Connector.UI.Base.Resources.Messages.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEcommerceMessages.
        /// </summary>
        internal static string GetEcommerceMessages {
            get {
                return ResourceManager.GetString("GetEcommerceMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEcommerceRecordCount.
        /// </summary>
        internal static string GetEcommerceRecordCount {
            get {
                return ResourceManager.GetString("GetEcommerceRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetErpMessages.
        /// </summary>
        internal static string GetErpMessages {
            get {
                return ResourceManager.GetString("GetErpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetErpOrderValue.
        /// </summary>
        internal static string GetErpOrderValue {
            get {
                return ResourceManager.GetString("GetErpOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetErpRecordCount.
        /// </summary>
        internal static string GetErpRecordCount {
            get {
                return ResourceManager.GetString("GetErpRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMagentoOrderValue.
        /// </summary>
        internal static string GetMagentoOrderValue {
            get {
                return ResourceManager.GetString("GetMagentoOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEntityActiveForReverseSync.
        /// </summary>
        internal static string IsEntityActiveForReverseSync {
            get {
                return ResourceManager.GetString("IsEntityActiveForReverseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrepareMessageQueueDetailsResponseEntity.
        /// </summary>
        internal static string PrepareMessageQueueDetailsResponseEntity {
            get {
                return ResourceManager.GetString("PrepareMessageQueueDetailsResponseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveEcommerceMessageQueueDetails.
        /// </summary>
        internal static string ReceiveEcommerceMessageQueueDetails {
            get {
                return ResourceManager.GetString("ReceiveEcommerceMessageQueueDetails", resourceCulture);
            }
        }
    }
}
